# Generated by Django 5.0.7 on 2025-03-23 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='conversaton',
            new_name='conversation',
        ),
    ]
